---
title: "Reproducible research in Price Statistics: Call for action!"
subtile: Overivew presented at the 2026 Ottawa Group (Warsaw, Poland)
authors:
- Serge Goussev
- Steve Martin
- Claude Lamboray
- Christophe Bontemps
- Tanya Flower
- Ben Hillman
- Caroline White
date: 2026-05-14
format:
  revealjs:
    menu:
      side: right
      width: wide
    slide-number: true
    show-slide-number: print
---

## Default approach to research in the discipline

-   Speak to why others should care
-   Examples where its hard... and where it doesn't have to be

## Why reproducibility?

-   What is reproducibility
-   How it helps an individual researcher
-   How it helps an NSO
-   How it helps the whole discipline

## Key principles

-   Use data that is well described (and ideally open)
-   Use version control + other principles for the research compedium
-   Publish a mutable copy of the compendium 
-   Cite various things...

## Deep dive on the compendium

-   Structure, docs, automation (i.e. RAP principles)

## Deep dive on data: open data

-   Gold standard as it could be used to benchmark methodological research + pedogogical reasons
-   Demo the open data catalog

## Deep dive on data: more locked versions of the data

-   Internal data 
-   Proprierary data

## Deep dive on publishing

-   Publish your compendium
-   Metadata of the research process (and other types)
-   How to reference various objects in your research

## What is next for reproducibility?

-   Workstream next steps
-   Next steps instilling the process with NSOs/researchers
