---
title: "About this project"
date-modified: last-modified
date-format: YYYY-MM-DD
format:
  html:
    toc: true
    toc-expand: 2
    other-links:
        - text: "Home page of the Scanner Data Task Team on the UN CEBD site"
          href: https://unstats.un.org/bigdata/task-teams/scanner/index.cshtml
---

This project is led by Workstream 5 of the [UN Task Team on Scanner data](https://unstats.un.org/bigdata/task-teams/scanner/index.cshtml), part of the [UN Committee of Experts on Big Data and Data Science for Official Statistics (UN-CEBD)](https://unstats.un.org/bigdata/index.cshtml).

# About the project

## What this project aims to do

Research in the price statistics discipline is not as reproducible as it could be. Most researchers utilize proprietary datasets and don't publish the code alongside the research so that a specific methodology or finding can be easily reproduced. The idea of this project is to help in both topics! We aim to:

-   Provide clear and approachable guidance on how researchers in price statistics can make their projects reproducible (including by learning new skills, by understanding how to publish and cite code, and many other topics).
-   Support cataloging open datasets that can be used as benchmarks to use for research purposes. The idea is to have all findings trialed and demonstrated on open benchmark datasets.

The project also builds on great efforts of early promoters of open science in the discipline![^1] We are aiming to continue to build momentum and make it easier for researchers to work openly!

[^1]: Notable early efforts include but are not limited to [Frances Krsinich publishing the FEWS package with open data in 2018](https://code.officialstatistics.org/scanner-task-team-gwg/FEWS_package), [Jens Mehrhoff showcasing the open Dominick's Finer Foods scanner dataset in 2019](https://github.com/eurostat/dff), [Erwin Dielert and Chihiro Shimizu opening a dataset of japanese laptop sales](https://unece.org/sites/default/files/2023-06/6.3%20Diewert%20and%20Shimizu%20Scanner%20Data%20Product%20Churn%20and%20Quality%20Adjustment%E3%80%80new.pdf), or [Jacek Białek including datasets with the PriceIndices R package](https://github.com/JacekBialek/PriceIndices/tree/master?tab=readme-ov-file#ad1).

## What this project does not aim to do

::: callout-warning
## This section is still a WIP

Not all team members are listed, we will update this section soon.
:::

As there is a lot of great guidance on the topic already, including [The Turing Way](https://book.the-turing-way.org/), [Reproducible Analytical Pipelines or RAP](https://nhsdigital.github.io/rap-community-of-practice/introduction_to_RAP/what_is_RAP/), and many more resources—the idea is to distill key information for the price statistics community, not to create a new standard.

## Presentations by the team

The team have presented to various group over the years:

- [Presentation at the 2025 CPI Expert Group (Geneva, Switzerland)](https://unece.org/sites/default/files/2025-04/1.3_UN%20Task%20Team.pdf) (see slides 9-13).
- [Presentation at the 2026 Ottawa Group (Warsaw, Poland)](/docs/presentations/OG2026/index.qmd)

# Project team members

The following are current or historic members of Workstream 5 of the UN Task Team.

## Serge Goussev [{{< fa brands orcid >}}](https://orcid.org/0009-0008-2359-5322) [{{< fa brands github >}}](https://github.com/sergegoussev)

-   Role: Workstream lead (2024 - current)
-   Email: [serge.goussev\@statcan.gc.ca](mailto:serge.goussev@statcan.gc.ca)

## Steve Martin [{{< fa brands orcid >}}](https://orcid.org/0000-0003-2544-9480) [{{< fa brands github >}}](https://github.com/marberts)

-   Role: Contributor (2024 - current)

## Claude Lamboray [{{< fa brands github >}}](https://github.com/clambora)

-   Role: Contributor (2024 - current)

## Christophe Bontemps [{{< fa brands github >}}](https://github.com/XtopheB)

-   Role: Contributor (2024 - current)

## Tanya Flower [{{< fa brands github >}}](https://github.com/tanyaflower-ons)

-   Role: Contributor (2024 - current)

## Ben Hillman [{{< fa brands github >}}](https://github.com/ONSBen)

-   Role: Contributor (2024 - current)

## Caroline White [{{< fa brands github >}}](https://github.com/carolinewsc)

-   Role: Contributor (2024 - current)

## Jens Mehrhoff

-   Role: Contributor (2024)